### ISSUE TITLE
Setting Gauge32 type OID fails

### ISSUE THREAD

**Issue by NetForces** [swisscom/ruby-netsnmp#12]
Sample code:

```
require 'netsnmp'
manager2 = NETSNMP::Client.new(host: "10.81.35.132", community: "public", version: "1")

manager2.set(oid: "1.3.6.1.2.1.17.7.1.4.5.1.1.1", value: 1000)

manager2.close
```

Result:

```
/Users/courchea/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/netsnmp-0.1.3/lib/netsnmp/client.rb:143:in `rescue in handle_retries': uninitiali
zed constant NETSNMP::Client::Timeout (NameError)
Did you mean?  Time
        from /Users/courchea/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/netsnmp-0.1.3/lib/netsnmp/client.rb:141:in `handle_retries'
        from /Users/courchea/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/netsnmp-0.1.3/lib/netsnmp/client.rb:130:in `set'

        from test.rb:5:in `<main>'
```

Trying via the CLI `snmpset` works:

```
snmpset -c public -v1 10.81.35.132 1.3.6.1.2.1.17.7.1.4.5.1
.1.1 u 1000
SNMPv2-SMI::mib-2.17.7.1.4.5.1.1.1 = Gauge32: 1000
```

cc @mdeloupy

**Comment by HoneyryderChuck** [comment]
For non-conventional types you must pass the :type parameter, in your case with :gauge, if I recall correctly

**Comment by NetForces** [comment]
Yup that worked but it got an error about this nor existing:

https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/client.rb#L143

Made the following change and worked:

```
diff --git a/lib/netsnmp/errors.rb b/lib/netsnmp/errors.rb
index e85aafd..da55f16 100644
--- a/lib/netsnmp/errors.rb
+++ b/lib/netsnmp/errors.rb
@@ -4,4 +4,5 @@ module NETSNMP
   Error = Class.new(StandardError)
   ConnectionFailed = Class.new(Error)
   AuthenticationFailed = Class.new(Error)
+  Timeout = Class.new(Error)
 end
```

I'll close this ticket and re-open a new one about the Timeout error as it's outside the scope of this ticket.
