### ISSUE TITLE
`Timeout::Error` does not exists

### ISSUE THREAD

**Issue by NetForces** [swisscom/ruby-netsnmp#13]

**Comment by NetForces** [comment]
```
/Users/courchea/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/netsnmp-0.1.3/lib/netsnmp/client.rb:143:in `rescue in handle_retries': uninitiali
zed constant NETSNMP::Client::Timeout (NameError)
Did you mean?  Time
        from /Users/courchea/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/netsnmp-0.1.3/lib/netsnmp/client.rb:141:in `handle_retries'
        from /Users/courchea/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/netsnmp-0.1.3/lib/netsnmp/client.rb:130:in `set'
        from test.rb:5:in `<main>'
```
