### ISSUE TITLE
Occasional "Decryption error" with SNMPv3

### ISSUE THREAD

**Issue by Sebbb** [swisscom/ruby-netsnmp#53]
Hello,

Note: This was most likely introduced in 0.4.2, after downgrading to 0.4.1 the issues disappeared.

Occasionally*, I get the following error:

/usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/v3_session.rb:100:in `decode': Decryption error (NETSNMP::Error)

I traced it down, it's not a network issue, according to wireshark the sent packet is already malformed. I also compared the hex output from debug with the sent packet in Wireshark, there's no difference.

So I assume there's something wrong with the ruby code generating the get-packet.

Initalization:
```
      class Secrets
        def self.snmp_user
                "Influx"
        end
        def self.snmp_auth_password
                'aWL6DUI2hdo823D'
        end
        def self.snmp_priv_password
                'WLGD2gdo72dh832'
        end
      end
      manager = NETSNMP::Client.new(host: ip_address, port: 161, username: Secrets.snmp_user,
        auth_password: Secrets.snmp_auth_password, auth_protocol: "sha",
        priv_password: Secrets.snmp_priv_password, priv_protocol: "aes",
        retry: 10, debug: $stderr, debug_level: 2)
```

Query:
```
      oids = %w(IF-MIB::ifHCOutOctets IF-MIB::ifHCInOctets IF-MIB::ifInErrors IF-MIB::ifOutErrors IF-MIB::ifInDiscards IF-MIB::ifOutDiscards)
      puts "*****************walk2" if debug
      oids.each{|oid|
        manager.walk(oid: oid).each {|oid_code, value|
        [...]
```

Output including debug:
```
[....]

sending request...

pdu: 3039
        engine_id: 0411 8000 1f88 0430 3133 3130 3130 3132 3132 ("\x80\x00\x1F\x88\x04013101012120")
        context: 0400 ("")
        request: a122
                request_id: 0204 053b 35d5 ("87766485")
                error: 0201 ("0")
                error_index: 0201 ("0")
                varbinds: 3014
                        Sequence: 3012
                                ObjectId: 060e 2b06 0102 0102 0201 0e81 eeb6 9e38 ("1.3.6.1.2.1.2.2.1.14.500010808")
                                Null: 0500

encoding PDU in V3 message...

security_params: 303b
        engine_id: 0411 8000 1f88 0430 3133 3130 3130 3132 3132 ("\x80\x00\x1F\x88\x04013101012120")
        engine_boots: 0201 ("12")
        engine_time: 0203 1efa ("2030242")
        username: 0406 496e 666c 7578 ("Influx")
        auth_mask: 040c 0000 0000 0000 0000 0000 0000 ("\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000")
        salt: 0408 0000 0000 0000 008e ("\x00\x00\x00\x00\x00\x00\x00\x8E")

v3_message: 3081
        message_version: 0201 ("3")
        headers: 3011
                message_id: 0204 784e 3854 ("2018392148")
                max_message_size: 0203 00ff ("65507")
                message_flags: 0401 ("\a")
                security_model: 0201 ("3")
        security_params: 043d 303b 0411 8000 1f88 0430 3133 3130 3130 3132 3132 3002 010c 0203 1efa a204 0649 6e66 6c75 7804 0c00 0000 0000 0000 0000 0000 0004 0800 0000 0000 0000 ("0;\x04\x11\x80\x00\x1F\x88\x04013101012120\x02\x01\f\x02\x03\x1E\xFA\xA2\x04\x06Influx\x04\f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x00\x8E")
        encrypted_pdu: 0440 cacb d443 362a e0a8 2fa8 2867 f5d6 cb19 b6b3 a33c f396 c85c e87f 3593 dda4 9130 c5fe 4479 8bc9 8bce 3b58 9c19 f8d4 998a b3b3 68e8 0abb 972c e96d 0984 df82 1ff2 ("\xCA\xCB\xD4C6*\xE0\xA8/\xA8(g\xF5\xD6\xCB\x19\xB6\xB3\xA3<\xF3\x96\xC8\\\xE8\x7F5\x93\xDD\xA4\x910\xC5\xFEDy\x8B\xC9\x8B\xCE;X\x9C\x19\xF8\xD4\x99\x8A\xB3\xB3h\xE8\n\xBB\x97,\xE9m\t\x84\xDF\x82\x1F\xF2")

3081 9702 0103 3011 0204 784e 3854 0203
00ff e304 0107 0201 0304 3d30 3b04 1180
001f 8804 3031 3331 3031 3031 3231 3230
0201 0c02 031e faa2 0406 496e 666c 7578
040c 0000 0000 0000 0000 0000 0000 0408
0000 0000 0000 008e 0440 cacb d443 362a
e0a8 2fa8 2867 f5d6 cb19 b6b3 a33c f396
c85c e87f 3593 dda4 9130 c5fe 4479 8bc9
8bce 3b58 9c19 f8d4 998a b3b3 68e8 0abb
972c e96d 0984 df82 1ff2

signing V3 message...

auth: 040c 885e 4e3e 6a8c c189 9e5c 3052 ("\x88^N>j\x8C\xC1\x89\x9E\\0R")

3081 9702 0103 3011 0204 784e 3854 0203
00ff e304 0107 0201 0304 3d30 3b04 1180
001f 8804 3031 3331 3031 3031 3231 3230
0201 0c02 031e faa2 0406 496e 666c 7578
040c 885e 4e3e 6a8c c189 9e04 0c00 0000
0000 0000 0000 0000 0052 0408 0000 0000
0000 008e 0440 cacb d443 362a e0a8 2fa8
2867 f5d6 cb19 b6b3 a33c f396 c85c e87f
3593 dda4 9130 c5fe 4479 8bc9 8bce 3b58
9c19 f8d4 998a b3b3 68e8 0abb 972c e96d
0984 df82 1ff2

received encoded V3 message

3077 0201 0330 1102 0478 4e38 5402 0300
ffe3 0401 0002 0103 0429 3027 0411 8000
1f88 0430 3133 3130 3130 3132 3132 3002
010c 0203 1efa a504 0649 6e66 6c75 7804
0004 0030 3404 1180 001f 8804 3031 3331
3031 3031 3231 3230 0400 a81d 0201 0002
0100 0201 0030 1230 1006 0a2b 0601 0603
0f01 0106 0041 0209

v3_message: 3077
        message_version: 0201 ("3")
        headers: 3011
                Integer: 0204 784e 3854 ("2018392148")
                Integer: 0203 00ff ("65507")
                message_flags: 0401 ("\x00")
                Integer: 0201 ("3")
        security_params: 0429 3027 0411 8000 1f88 0430 3133 3130 3130 3132 3132 3002 010c 0203 1efa a504 0649 6e66 6c75 7804 0004 ("0'\x04\x11\x80\x00\x1F\x88\x04013101012120\x02\x01\f\x02\x03\x1E\xFA\xA5\x04\x06Influx\x04\x00\x04\x00")
        pdu: 3034
                OctetString: 0411 8000 1f88 0430 3133 3130 3130 3132 3132 ("\x80\x00\x1F\x88\x04013101012120")
                OctetString: 0400 ("")
                ASN1Data: a81d
                        Integer: 0201 ("0")
                        Integer: 0201 ("0")
                        Integer: 0201 ("0")
                        Sequence: 3012
                                Sequence: 3010
                                        ObjectId: 060a 2b06 0106 030f 0101 0600 ("1.3.6.1.6.3.15.1.1.6.0")
                                        ASN1Data: 4102 0954

security_params: 3027
        engine_id: 0411 8000 1f88 0430 3133 3130 3130 3132 3132 ("\x80\x00\x1F\x88\x04013101012120")
        engine_boots: 0201 ("12")
        engine_time: 0203 1efa ("2030245")
        username: 0406 496e 666c 7578 ("Influx")
        auth_param: 0400 ("")
        priv_param: 0400 ("")

received response PDU

pdu: 3034
        engine_id: 0411 8000 1f88 0430 3133 3130 3130 3132 3132 ("\x80\x00\x1F\x88\x04013101012120")
        context: 0400 ("")
        request: a81d
                request_id: 0201 ("0")
                error: 0201 ("0")
                error_index: 0201 ("0")
                varbinds: 3012
                        Sequence: 3010
                                ObjectId: 060a 2b06 0106 030f 0101 0600 ("1.3.6.1.6.3.15.1.1.6.0")
                                Integer: 0202 0954 ("2388")
Error while querying:
Traceback (most recent call last):
        10: from snmp.rb:101:in `each'
         9: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:84:in `block in walk'
         8: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:84:in `catch'
         7: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:85:in `block (2 levels) in walk'
         6: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:85:in `loop'
         5: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:86:in `block (3 levels) in walk'
         4: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:67:in `get_next'
         3: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:155:in `handle_retries'
         2: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:67:in `block in get_next'
         1: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/v3_session.rb:27:in `send'
/usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/v3_session.rb:100:in `decode': Decryption error (NETSNMP::Error)

```
Full trace from beginning to end is available as well as a pcap file.

What information do you need to find the reason of this issue?

Environment: netsnmp-0.4.2, ruby-2.7.3, SNMP server: Palo Alto Firewall with PAN-OS 9.1.4

*Occasionally: I currently query 10 firewalls for various traffic statistics, the script finishes without any error around 50% of the  time.

Thanks
Sebastian

**Comment by HoneyryderChuck** [comment]
Hi Sebastian,

It seems you're getting the `usmStatsDecryptionErrors` report PDU back. This was a [recent change](https://github.com/swisscom/ruby-netsnmp/blob/master/CHANGELOG.md#042).

**Comment by Sebbb** [comment]
Hello,

I now downgraded to 0.4.1 and it's working as before. The more interesting question is, was this error just silently dropped before and we just did not receive an answer for a specific oid, but didn't notice it? Because I can see, already the outgoing packet generated by netsnmp was malformed, according to the wireshark output.

The whole netsnmp debug log is quite large, I have it for this one .walk comment, but not for the initalisiation of the manger object. Does this help?

Sebastian

**Comment by HoneyryderChuck** [comment]
And with `0.4.1`, what's the value returned by the agent? `2388`?

> was this error just silently dropped before and we just did not receive an answer for a specific oid, but didn't notice it? 

I think so. Looking at the dump you sent, in v0.4.1, it's just decodes the packet and returns the value, and doesn't perform any analysis on the return PDU's OID, which is dodgy, and now surfaces an error. The meaning of the error is probably clear to you, since you identified that the send PDU was malformed: The agent couldn't decrypt the incoming PDU.

Can I ask what do you mean by "already the outgoing packet generated by netsnmp was malformed", or more specifically, which part do you identify as malformed? That would help to narrow down what's going on.

**Comment by Sebbb** [comment]
Hello,

> Can I ask what do you mean by "already the outgoing packet generated by netsnmp was malformed", or more specifically, which part do you identify as malformed?

sure:

![image](https://user-images.githubusercontent.com/4967941/123639098-28ccde00-d820-11eb-8c31-829fe3b3c284.png)

(Captured on the Linux host itself). So according to both Wireshark and the destination device, the packet generated by netsnmp is malformed. Unfortunately, as I'm not familar with the SNMP data structure, I can't tell you what's wrong in detail.

Sebastian

**Comment by HoneyryderChuck** [comment]
Now that I had a better look at it, I'm highly suspitious of that salt param, a few messages above:

```
username: 0406 496e 666c 7578 ("Influx")
        auth_mask: 040c 0000 0000 0000 0000 0000 0000 ("\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000")
        salt: 0408 0000 0000 0000 008e ("\x00\x00\x00\x00\x00\x00\x00\x8E")
```

That salt there looks little... "random". Could you run this again, and somehow set a breakpoint when the error happens, and figure out [what's the state here](https://github.com/swisscom/ruby-netsnmp/blob/master/lib/netsnmp/encryption/aes.rb#L49-L63)? I'm mostly interested in knowing which `@local`.

This kind of errors is a bit hard to narrow down without having access to the specific environment where you reproduce it. In case that's an avenue your employers would consider, [it has been done before](https://github.com/swisscom/ruby-netsnmp/issues/40).

**Comment by Sebbb** [comment]
Hello,

at least the salt does not look different to the requests before, where it worked fine.

```
# grep salt snmp_debugoutput |tail
        salt: 0408 0000 0000 0000 0085 ("\x00\x00\x00\x00\x00\x00\x00\x85")
        salt: 0408 0000 0000 0000 0086 ("\x00\x00\x00\x00\x00\x00\x00\x86")
        salt: 0408 0000 0000 0000 0087 ("\x00\x00\x00\x00\x00\x00\x00\x87")
        salt: 0408 0000 0000 0000 0088 ("\x00\x00\x00\x00\x00\x00\x00\x88")
        salt: 0408 0000 0000 0000 0089 ("\x00\x00\x00\x00\x00\x00\x00\x89")
        salt: 0408 0000 0000 0000 008a ("\x00\x00\x00\x00\x00\x00\x00\x8A")
        salt: 0408 0000 0000 0000 008b ("\x00\x00\x00\x00\x00\x00\x00\x8B")
        salt: 0408 0000 0000 0000 008c ("\x00\x00\x00\x00\x00\x00\x00\x8C")
        salt: 0408 0000 0000 0000 008d ("\x00\x00\x00\x00\x00\x00\x00\x8D")
        salt: 0408 0000 0000 0000 008e ("\x00\x00\x00\x00\x00\x00\x00\x8E")
```

So I added some debug output to this function:
`        pp [:iv, iv, :salt, salt, :local, @local, :time, time, :boots, boots]
`

Result:

```[:iv,
 "\x00\x00\x00\r\x00'\xB2\x89\x00\x00\x00\x00\x00\x00\x00\x0E",
 :salt,
 "\x00\x00\x00\x00\x00\x00\x00\x0E",
 :local,
 15,
 :time,
 2601609,
 :boots,
 13]
[:iv,
 "\x00\x00\x00\r\x00'\xB2\x89\x00\x00\x00\x00\x00\x00\x00\x0F",
 :salt,
 "\x00\x00\x00\x00\x00\x00\x00\x0F",
 :local,
 16,
 :time,
 2601609,
 :boots,
 13]
[:iv,
 "\x00\x00\x00\r\x00'\xB2\x89\x00\x00\x00\x00\x00\x00\x00\x10",
 :salt,
 "\x00\x00\x00\x00\x00\x00\x00\x10",
 :local,
 17,
 :time,
 2601609,
 :boots,
 13]
Traceback (most recent call last):
        10: from snmp.rb:101:in `each'
         9: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:84:in `block in walk'
         8: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:84:in `catch'
         7: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:85:in `block (2 levels) in walk'
         6: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:85:in `loop'
         5: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:86:in `block (3 levels) in walk'
         4: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:67:in `get_next'
         3: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:155:in `handle_retries'
         2: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/client.rb:67:in `block in get_next'
         1: from /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/v3_session.rb:27:in `send'
/usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/v3_session.rb:100:in `decode': Decryption error (NETSNMP::Error)
```

Is that what you expected?

Sebastian

**Comment by HoneyryderChuck** [comment]
True, the salt is incremental, nothing serious.

One question: if you do multiple "walk" runs, does it fail always on the same ID?

Also, picking up on your example above, it'd be interesting to have the `NETSNMP_DEBUG` log from at least the last 4 exchanged PDUs before it breaks. I'm wondering whether there's smth from the agent `netsnmp` should act upon.

**Comment by Sebbb** [comment]
Nope, completly random fails. Sometime it also passes without any failure..

Longer debug output is here:

https://pastebin.com/Qyse33ZY

**Comment by HoneyryderChuck** [comment]
Ok, I think I see something suspitious in your pastebin. Leaving here for later analysis:

```
auth: 040c 885e 4e3e 6a8c c189 9e5c 3052 ("\x88^N>j\x8C\xC1\x89\x9E\\0R")
 
3081 9702 0103 3011 0204 784e 3854 0203
00ff e304 0107 0201 0304 3d30 3b04 1180
001f 8804 3031 3331 3031 3031 3231 3230
0201 0c02 031e faa2 0406 496e 666c 7578
040c 885e 4e3e 6a8c c189 9e04 0c00 0000
0000 0000 0000 0000 0052 0408 0000 0000
0000 008e 0440 cacb d443 362a e0a8 2fa8
2867 f5d6 cb19 b6b3 a33c f396 c85c e87f
3593 dda4 9130 c5fe 4479 8bc9 8bce 3b58
9c19 f8d4 998a b3b3 68e8 0abb 972c e96d
0984 df82 1ff2
```

The auth signature doesn't appear to be sent fully to the packet:

* `040c 885e 4e3e 6a8c c189 9e5c 3052`
* `040c 885e 4e3e 6a8c c189 9e04 0c00` (5th row)

**Comment by Sebbb** [comment]
Hello,

it always seems to be "\x04\f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"

I added
```
--- /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/message.rb.orig       2021-07-05 12:02:45.804510080 +0200
+++ /usr/local/rvm/gems/ruby-2.7.3/gems/netsnmp-0.4.2/lib/netsnmp/message.rb    2021-07-05 12:02:48.132545499 +0200
@@ -120,6 +120,7 @@
         log { "signing V3 message..." }
         auth_salt = OpenSSL::ASN1::OctetString.new(signature).with_label(:auth)
         log(level: 2) { auth_salt.to_hex }
+        pp [:AUTHNONE, AUTHNONE, :to_der, AUTHNONE.to_der]
         encoded.sub!(AUTHNONE.to_der, auth_salt.to_der)
         log { Hexdump.dump(encoded) }
       end
```

Full result: https://pastebin.com/SZ8ba3YN

Sebastian

**Comment by HoneyryderChuck** [comment]
I think I managed to reproduce it. You are right, some segments get corrupted, and yes, the problem is that exact line.

Will see about issuing a fix for you to test.

**Comment by HoneyryderChuck** [comment]
@Sebbb can you retry your example using the `issue-53` branch?

**Comment by Sebbb** [comment]
@HoneyryderChuck Tried it several times, wasn't able to reproduce the issue anymore.

Thanks!
Sebastian

**Comment by HoneyryderChuck** [comment]
Great to hear! Will merge and close. Thx for the patience!
